### ISSUE TITLE
Database Question

### ISSUE THREAD

**Issue by jonBarcus** [jonBarcus/SoIaF_GM_Tools#1]
Okay, so I need your guys input and some expertise.

The basic question is about using an array in the Character table for "Abilities."  Then, do we have the "Specialties" connected to a Character or to Abilities?  There are a few ways we can do things, I believe, and I think to answer that question you'll both need to have a little better understanding of ActiveRecord in Rails.

**Comment by jonBarcus** [comment]
Trying to assign more than one person...but it doesn't seem that I can do so.  We can, however, all contribute to the discussion.

**Comment by kirejm** [comment]
Can you use an array in a table? I figured it would make more sense for a separate column for each ability...

-----Original Message-----

**Comment by drumsetz** [comment]
I was also under the impression that you couldn't use an array in a table (though it has been a while since I have done much database work).

I had thought that if you wanted that in order to get a 1 to many relationship in a database you were best off making a new table for the "many" item.

In this case you'd create an "Abilities" table that had a primary key of characterId and then had a separate row for each ability associated with that character.

I don't know how that model fits with Rail's ActiveRecord model, though.

**Comment by jonBarcus** [comment]
I think it has to do with ActiveRecord and Postgresql.  If you take a look at [this project](https://github.com/jonBarcus/Pup-Promenade/blob/master/db/schema.rb) and scroll all the day to the bottom of the schema, you'll see we used an integer, setting array as true, which then allowed us to store multiple integers in that column.

I'll make a test app today or tomorrow to do a test of concept again.

Another possibility is using the postgresql datatype of hstore.  Though from my quick looks at hstore, that seems to store key/value pairs, which I'm not sure is something that is preferable.

**Comment by kirejm** [comment]
It feels like it might be limiting to mask it within an array -- I know one
thing I would be interested on trying is just doing straight SELECT queries
and aggregates using the base ability scores (and putting them in an array
would be a complex way to de-package them, I think).

I guess the question is, would it give a big advantage to use an array or
key:value set rather than a table?

2015-03-22 8:37 GMT-07:00 Jonathan Barcus notifications@github.com:

**Comment by drumsetz** [comment]
Looking at the project referenced, I think that schema is using a separate table for neighborhoods, and then just referencing that set of neighborhoods using the array of _ids in the walkers table.

That schema may actually expand into a database with a separate neighborhoods table with the 1:many relationship between walkers and neighborhoods and not actually place any neighborhood information into the walkers table.

That additional info in the schema just sets up the relationship and tells Rails how to set up the records so that you have the appropriate accessors when writing the Ruby code. I'll clone that repo and see if I can get a view on the created db to confirm.

**Comment by drumsetz** [comment]
I did a little more digging on this and it seems that using the array would work pretty well, and you can even use the array in SELECT queries...

Select \* from t1 join t2 on t1.id = any( t2.ids );

I was able to do something like that on the pup promenade database that was using this feature. I haven't looked to see how the Ruby code references this yet.

I also should get a better idea of the abilities versus specialties so I can address the actual original question.

**Comment by jonBarcus** [comment]
Still working out the kinks in the proof of concept app. Once I have that finished I'll push it up for you guys to look at.

**Comment by jonBarcus** [comment]
Okay, here's the [VERY basic proof of concept](https://github.com/jonBarcus/Test_App) for ActiveRecord I made for you guys.  Take a quick look, and maybe we can arrange a time to get on a HangOut and work together/discuss things about the database soon.  I'm free all weekend.

**Comment by jonBarcus** [comment]
Per our Saturday discussion:

We've decided to do a series of join tables (*_id, *_id, etc.).

Closing this issue and will be pushing work in the next couple of days.
