### ISSUE TITLE
House "No House" is deleteable

### ISSUE THREAD

**Issue by kirejm** [jonBarcus/SoIaF_GM_Tools#7]
This probably should be a special case that cannot ever be removed/modified.

**Comment by drumsetz** [comment]
I modified the controller (via the new HouseMaintenance module) so that when the user attempts to delete the "No House" the controller will simply ignore it.

The user will still be able to modify the name of "No House" so we should fix that, too (since right now you can change the name and then delete it -- and the way I coded up the fix was in such a way that if you change "No House" then no houses will ever be deleted, I believe).

**Comment by drumsetz** [comment]
#18 should resolve this issue
